# -*- coding: utf-8 -*-
"""Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xZR3K-80FG-bNkjoMI9Gnkf6vxoNg-kX
"""

print(dir(str))

a = "Hello world"
b = a.upper()
c = a.swapcase()
d = a.replace('world', 'universe')
print(b)
print(c)
print(d)

a = '1234ab'
b = a.isdigit()
print(b)

a=range(10)
b = list(a)
print(b)
print(a)

#start,stop then steps
my_list = list(range(5,15,2))
print(my_list)

def add_numbers(a,b):
  result = a + b
  return result
print(add_numbers(10,4))

def greet(name, greeting="hello"):
  print(f"{greeting}, {name}!")

correct_username = 'admin'
correct_password = '1234'
while True:
  username = input("Enter your Username: ")
  password = input("Enter your password: ")
  if username == correct_username and password == correct_password:
    print("Login successful")
    break
  else:
    print("Invalid username or password.please try again")

numbers = [1,5,4,7,8,6]
total = sum(numbers)
maximum = max(numbers)
sorted_numbers = sorted(numbers)
print("Numbers:", numbers)
print("Sum:", total)
print("Maximum:", maximum)
print("Sorted:", sorted_numbers)

name = "Deekshitha"
age = 20
college = "Malla Reddy University"
while True:
  name_1 = input("Enter your name: ")
  age_1 = int(input("Enter your age: "))
  college_1 = input("Enter your college: ")
  if name_1 == name and age_1 == age and college_1 == college:
    print("profile is correct")
    break
  else:
    print("profile is wrong")