# -*- coding: utf-8 -*-
"""python basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_suOBW-grbVPQhmuX9JoTUugA_T7rzk
"""

list = ["apple","banana","carrot"]
print(list)

t = ['a','b','c','d','e']
t[1:3]
t[:4]
t[3:]

age = [78,75,100]
No.of.hours = [2,7,]

my_list = [1,'hello',3.14,True]
print("Original Integer:",my_list)
my_list.append('world')
print("List after appending 'world':",my_list)
my_list.remove(3.14)
print("List after removing 3.14:",my_list)

my_tuple = (1, 'apple', 3.14,False)
print("Original Tuple:",my_tuple)
print("First element:",my_tuple[0])
print("Last element:",my_tuple[-1])



for i in range(1,6):
  print(i)

i = 1
while i <= 5:
  print(i)
  i += 1

number=int(input("Enter a number: "))
if number > 0:
  print("The number is positive.")
elif number < 0:
  print("The number is negative.")
else:
  print("The number is zero.")

def greet(name):
  """This function takes a name as an argument and prints a greeting."""
  print(f"Hello from function,{name}!")
greet("Alice")